### ISSUE TITLE
conf-libX11 fails to install on macOS

### ISSUE THREAD

**Issue by vogler** [ocaml/opam-repository#13686]
Upgrade `graphics 1.0 to 4.07.1` failed because of missing permission for `execvp()` in `sandbox.sh`:
![image](https://user-images.githubusercontent.com/493741/54525588-d334d600-4974-11e9-8aa2-c87404fa4096.png)
Without the sandbox I can execute the line `PKG_CONFIG_PATH=$PKG_CONFIG_PATH/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig pkg-config x11
` without errors.

macOS 10.14.3 (18D42)
opam 2.0.3

**Comment by mseri** [comment]
Can you try to do it again after running `opam update`?

**Comment by vogler** [comment]
Still the same.
Recompilation of `lablgtk` also failed:

~~~
#=== ERROR while compiling lablgtk.2.18.7 =====================================#
# context     2.0.3 | macos/x86_64 | ocaml-variants.4.07.1+afl | https://opam.ocaml.org/#55e835f1
# path        ~/.opam/4.07.1+afl/.opam-switch/build/lablgtk.2.18.7
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure --prefix /Users/voglerr/.opam/4.07.1+afl LABLGLDIR=/Users/voglerr/.opam/4.07.1+afl/lib/lablgl
# exit-code   1
# env-file    ~/.opam/log/lablgtk-37488-81614a.env
# output-file ~/.opam/log/lablgtk-37488-81614a.out
### output ###
# [...]
# checking for suffix of object files... o
# checking whether we are using the GNU C compiler... yes
# checking whether cc accepts -g... yes
# checking for cc option to accept ISO C89... none needed
# checking whether C compiler accepts -fno-unwind-tables... yes
# checking platform... Unix
# checking native dynlink... checking for pkg-config... /usr/local/bin/pkg-config
# checking for GTK+ - version >= 2.0.0... no
# *** Could not run GTK+ test program, checking why...
# *** The test program failed to compile or link. See the file config.log for the
# *** exact error that occured. This usually means GTK+ is incorrectly installed.
# configure: error: GTK+ is required
~~~

GTK+ is installed and expat available:
~~~
❯ brew info gtk
gtk+: stable 2.24.32 (bottled), HEAD
GUI toolkit
https://gtk.org/
/usr/local/Cellar/gtk+/2.24.32_2 (1,174 files, 50.6MB) *
  Poured from bottle on 2018-03-22 at 13:22:58
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gtk+.rb
==> Dependencies
Build: gobject-introspection ✔, pkg-config ✔
Required: atk ✔, gdk-pixbuf ✔, hicolor-icon-theme ✔, pango ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 6,984 (30 days), 25,823 (90 days), 159,257 (365 days)
install_on_request: 1,564 (30 days), 4,996 (90 days), 30,086 (365 days)
build_error: 0 (30 days)

~
❯ brew info expat
expat: stable 2.2.6 (bottled), HEAD [keg-only]
XML 1.0 parser
https://libexpat.github.io/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/expat.rb
==> Options
--HEAD
	Install HEAD version
==> Caveats
expat is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

==> Analytics
install: 8,292 (30 days), 20,629 (90 days), 31,494 (365 days)
install_on_request: 524 (30 days), 1,460 (90 days), 5,891 (365 days)
build_error: 0 (30 days)
~~~

**Comment by mseri** [comment]
Somebody seems to have had some success with 
```
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig/ opam install lablgtk
```

**Comment by vogler** [comment]
Ok, thanks, that helped with `lablgtk`, but for `conf-libX11` it seems to be a permission problem.

**Comment by mseri** [comment]
Indeed, the issue is that osx sandbox prevent execution from inside scripts. We need to move the invocation out of the script https://github.com/ocaml/opam-repository/blob/master/packages/conf-libX11/conf-libX11.1/files/pkg-osx.sh and back into the opam file for it to work

**Comment by mseri** [comment]
Like this: https://github.com/ocaml/opam-repository/blob/master/packages/conf-cairo/conf-cairo.1/opam#L8

I cannot make the PR right now, but I think that should fix it once and for all

**Comment by mseri** [comment]
PR is waiting for review. You can try the patch it and see if it helps.

**Comment by vogler** [comment]
Works - thank you!

**Comment by mseri** [comment]
Thanks for checking

**Comment by leon-gondelman** [comment]
Hello, 

After checking and updating opam, I still cannot install `conf-libX11 1` package :( 
Could someone help me to find out how to fix this ? 
Below is the installation error message output:

``` 
The following actions will be performed:
  - install conf-libX11 1

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of conf-libX11 failed at "/Users/apollo/.opam/opam-init/hooks/sandbox.sh build ./pkg-osx.sh".

#=== ERROR while compiling conf-libX11.1 ======================================#
# context     2.0.5 | macos/x86_64 | ocaml-base-compiler.4.07.1 | git+https://github.com/dra27/opam-repository.git#graphics
# path        ~/.opam/4.07.1/.opam-switch/build/conf-libX11.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./pkg-osx.sh
# exit-code   1
# env-file    ~/.opam/log/conf-libX11-27134-42bb52.env
# output-file ~/.opam/log/conf-libX11-27134-42bb52.out



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build conf-libX11 1
+- 
- No changes have been performed
```

**Comment by leon-gondelman** [comment]
Problem solved by installing XQuartz and reinstalling ocaml

**Comment by vogler** [comment]
Can we adjust the opam file of `lablgtk` as well? Any `opam upgrade` that contains it fails if I don't set the path like this:
~~~
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig opam upgrade
~~~
I could put it in my environment, but I assume all macOS/brew installations have this problem.

**Comment by vogler** [comment]
`PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig` is enough for `lablgtk`, the other two directories don't work since they don't have `libffi.pc`.
Can someone else on macOS confirm this, or is my setup somehow broken?

~~~
$ ls /usr/local/Cellar/libffi/3.2.1/lib/pkgconfig
libffi.pc
~~~

~~~
$ ls /usr/local/lib/pkgconfig
IlmBase.pc                gail.pc                                 jansson.pc            libpcre16.pc       mono-lineeditor.pc  python-3.7.pc
ImageMagick-7.Q16HDRI.pc  gdk-2.0.pc                              jasper.pc             libpcre2-16.pc     mono-options.pc     python-3.7m.pc
ImageMagick.pc            gdk-3.0.pc                              jemalloc.pc           libpcre2-32.pc     mono.pc             python.pc
Magick++-7.Q16HDRI.pc     gdk-pixbuf-2.0.pc                       lcms2.pc              libpcre2-8.pc      monodoc.pc          python2.pc
Magick++.pc               gdk-quartz-2.0.pc                       lept.pc               libpcre2-posix.pc  monosgen-2.pc       python3.pc
MagickCore-7.Q16HDRI.pc   gdk-quartz-3.0.pc                       libass.pc             libpcre32.pc       mozjs185.pc         reactive.pc
MagickCore.pc             gdlib.pc                                libassuan.pc          libpcrecpp.pc      mpfr.pc             rubberband.pc
MagickWand-7.Q16HDRI.pc   gio-2.0.pc                              libavcodec.pc         libpcreposix.pc    msgpack.pc          samplerate.pc
MagickWand.pc             gio-unix-2.0.pc                         libavdevice.pc        libpng.pc          netpbm.pc           sdl2.pc
OpenEXR.pc                glib-2.0.pc                             libavfilter.pc        libpng16.pc        nettle.pc           sndfile.pc
aom.pc                    gmodule-2.0.pc                          libavformat.pc        libpostproc.pc     nspr.pc             soxr-lsr.pc
aspnetwebstack.pc         gmodule-export-2.0.pc                   libavresample.pc      librtmp.pc         odbc.pc             soxr.pc
atk.pc                    gmodule-no-export-2.0.pc                libavutil.pc          libsmi.pc          odbccr.pc           speex.pc
bash.pc                   gnutls-dane.pc                          libbluray.pc          libssh.pc          odbcinst.pc         system.web.extensions.design_1.0.pc
cairo-fc.pc               gnutls.pc                               libcares.pc           libssh2.pc         ogg.pc              system.web.extensions_1.0.pc
cairo-ft.pc               gobject-2.0.pc                          libcdt.pc             libswresample.pc   oniguruma.pc        system.web.mvc.pc
cairo-gobject.pc          gobject-introspection-1.0.pc            libcerf.pc            libswscale.pc      opencore-amrnb.pc   system.web.mvc2.pc
cairo-pdf.pc              gobject-introspection-no-export-1.0.pc  libcgraph.pc          libtasn1.pc        opencore-amrwb.pc   system.web.mvc3.pc
cairo-png.pc              gpg-error.pc                            libde265.pc           libtiff-4.pc       opus.pc             termkey.pc
cairo-ps.pc               graphite2.pc                            libevent.pc           libunbound.pc      osxfuse.pc          tesseract.pc
cairo-quartz-font.pc      gthread-2.0.pc                          libevent_core.pc      libusb-1.0.pc      p11-kit-1.pc        theora.pc
cairo-quartz-image.pc     gtk+-2.0.pc                             libevent_extra.pc     libutf8proc.pc     pango.pc            theoradec.pc
cairo-quartz.pc           gtk+-3.0.pc                             libevent_openssl.pc   libuv.pc           pangocairo.pc       theoraenc.pc
cairo-script.pc           gtk+-quartz-2.0.pc                      libevent_pthreads.pc  libwebp.pc         pangoft2.pc         unibilium.pc
cairo-svg.pc              gtk+-quartz-3.0.pc                      libgit2.pc            libwebpdecoder.pc  pixman-1.pc         uuid.pc
cairo-tee.pc              gtk+-unix-print-2.0.pc                  libgvc.pc             libwebpdemux.pc    poppler-cairo.pc    vorbis.pc
cairo.pc                  gtk+-unix-print-3.0.pc                  libgvpr.pc            libwebpmux.pc      poppler-cpp.pc      vorbisenc.pc
cecil.pc                  gtk-mac-integration-gtk2.pc             libheif.pc            libxdot.pc         poppler-glib.pc     vorbisfile.pc
dotnet.pc                 gtk-mac-integration-gtk3.pc             libidn2.pc            libzmq.pc          poppler-qt5.pc      vpx.pc
dotnet35.pc               gtk-mac-integration.pc                  libjpeg.pc            lua-5.1.pc         poppler-splash.pc   vterm.pc
epoxy.pc                  gtksourceview-2.0.pc                    liblab_gamut.pc       lua-5.3.pc         poppler.pc          wcf.pc
flac++.pc                 gtksourceview-3.0.pc                    liblz4.pc             lua.pc             protobuf-lite.pc    x264.pc
flac.pc                   gts.pc                                  liblzma.pc            lua5.1.pc          protobuf.pc         x265.pc
fontconfig.pc             harfbuzz-gobject.pc                     libmaxminddb.pc       lua5.3.pc          py3cairo.pc         xbuild12.pc
freetype2.pc              harfbuzz-icu.pc                         libnghttp2.pc         luajit.pc          pycairo.pc          yaml-0.1.pc
frei0r.pc                 harfbuzz-subset.pc                      libntfs-3g.pc         lzo2.pc            pygobject-2.0.pc
fribidi.pc                harfbuzz.pc                             libopenjp2.pc         macfuse.pc         pygobject-3.0.pc
fuse.pc                   hogweed.pc                              libpathplan.pc        mono-2.pc          pygtk-2.0.pc
gail-3.0.pc               isl.pc                                  libpcre.pc            mono-cairo.pc      python-2.7.pc
~~~

~~~
$ ls /opt/X11/lib/pkgconfig
applewm.pc             cairo-xlib.pc      fontsproto.pc  pixman-1.pc        xaw3d.pc          xcb-icccm.pc        xcb-xf86dri.pc   xextproto.pc         xkbcomp.pc         xscrnsaver.pc
applewmproto.pc        cairo-xml.pc       fontutil.pc    presentproto.pc    xaw6.pc           xcb-image.pc        xcb-xfixes.pc    xf86bigfontproto.pc  xkbfile.pc         xshmfence.pc
bigreqsproto.pc        cairo.pc           freetype2.pc   printproto.pc      xaw7.pc           xcb-keysyms.pc      xcb-xinerama.pc  xf86dgaproto.pc      xkbui.pc           xt.pc
cairo-fc.pc            compositeproto.pc  gl.pc          pthread-stubs.pc   xcb-atom.pc       xcb-present.pc      xcb-xkb.pc       xf86driproto.pc      xmu.pc             xtrap.pc
cairo-ft.pc            damageproto.pc     glesv1_cm.pc   randrproto.pc      xcb-aux.pc        xcb-proto.pc        xcb-xtest.pc     xf86miscproto.pc     xmuu.pc            xtst.pc
cairo-pdf.pc           dmx.pc             glesv2.pc      recordproto.pc     xcb-composite.pc  xcb-randr.pc        xcb-xv.pc        xf86rushproto.pc     xorg-server.pc     xv.pc
cairo-png.pc           dmxproto.pc        glproto.pc     renderproto.pc     xcb-cursor.pc     xcb-record.pc       xcb-xvmc.pc      xf86vidmodeproto.pc  xp.pc              xvmc.pc
cairo-ps.pc            dri.pc             glu.pc         resourceproto.pc   xcb-damage.pc     xcb-render.pc       xcb.pc           xfixes.pc            xpm.pc             xxf86misc.pc
cairo-script.pc        dri2proto.pc       ice.pc         scrnsaverproto.pc  xcb-dpms.pc       xcb-renderutil.pc   xcmiscproto.pc   xfont.pc             xpresent.pc        xxf86vm.pc
cairo-svg.pc           dri3proto.pc       inputproto.pc  sm.pc              xcb-dri2.pc       xcb-res.pc          xcomposite.pc    xfont2.pc            xproto.pc
cairo-tee.pc           evieproto.pc       kbproto.pc     trapproto.pc       xcb-dri3.pc       xcb-screensaver.pc  xcursor.pc       xfontcache.pc        xproxymngproto.pc
cairo-xcb-shm.pc       fixesproto.pc      libfs.pc       videoproto.pc      xcb-errors.pc     xcb-shape.pc        xdamage.pc       xft.pc               xpyb.pc
cairo-xcb.pc           fontcacheproto.pc  libpng.pc      x11-xcb.pc         xcb-event.pc      xcb-shm.pc          xdmcp.pc         xi.pc                xrandr.pc
cairo-xlib-xcb.pc      fontconfig.pc      libpng16.pc    x11.pc             xcb-ewmh.pc       xcb-sync.pc         xevie.pc         xinerama.pc          xrender.pc
cairo-xlib-xrender.pc  fontenc.pc         osmesa.pc      xau.pc             xcb-glx.pc        xcb-util.pc         xext.pc          xineramaproto.pc     xres.pc
~~~

**Comment by simonelnahas** [comment]
Also experiencing this problem. Should a PR be made to update the environment variables?

**Comment by zebralight** [comment]
I'm also seeing this on Catalina 10.15.5 after reinstalling ocaml upon installing xquartz.  Is there another workaround for this issue?

**Comment by FayardProf** [comment]
Same problem here. On Big Sur 11.5.1, after reinstalling ocaml upon installing xquartz, i get the message "[WARNING] Opam package conf-libX11.1 depends on the following system package that can no longer be found: xquartz"

No way to use the Graphics module

**Comment by Goblin80** [comment]
I have encountered the same problem in a slightly different setup.

Solution for me was installing `libffi-dev` using the system's package manager.
