### ISSUE TITLE
deriving does not work

### ISSUE THREAD

**Issue by vzaliva** [ocaml/opam-repository#4103]
Deriving package does not seems to be working properly.
I am trying to use it under MacOS. After installing it via ‘opam install deriving”:

    $ ocaml
            OCaml version 4.02.1
      # #use "topfind";;
    - : unit = ()
    - : unit = ()
    # #camlp4o;;
    	Camlp4 Parsing version 4.02.1
    
    # #require "deriving.syntax";;
    

After that I did not get back # prompt. #list shows:

    ...
    deriving            (version: 0.7)
    deriving.runtime    (version: n/a)
    deriving.syntax     (version: n/a)
    deriving.syntax.classes (version: 0.7)
    deriving.syntax.common (version: n/a)
    deriving.syntax.std (version: 0.7)
    deriving.syntax.tc  (version: 0.7)
    deriving.syntax_tc  (version: n/a)
    deriving.tc         (version: n/a)
    …

It is a compatibility issue under MacOS? I will be glad to perform additional steps to debug.

**Comment by yallop** [comment]
Thanks for the report!  You may be running into [this issue](https://github.com/ocaml/camlp4/issues/48), in which case you can fix the problem by upgrading Camlp4.  You can check which version of Camlp4 you have installed using

```
opam list camlp4
```

The bug is in Camlp4 version 4.02.1, and is fixed in 4.02.1+1; you can upgrade by running

```
opam update
opam install camlp4.4.02.1+2
```

or just

```
opam update
opam upgrade camlp4
```

to install the latest version.

**Comment by vzaliva** [comment]
Thanks! I currently have camlp4 4.02.1+system installed, which reflects that I have camlp4 installed via MacPorts. Any advice how to switch to OPAM version? I tried upgrading:

    $ opam install camlp4.4.02.1+2
    [ERROR] camlp4.4.02.1+2 is not available because your system doesn't comply with !preinstalled &
            ocaml-version = "4.02.1".

I have right version:

    $ opam switch
    --     -- 3.11.2  Official 3.11.2 release
    --     -- 3.12.1  Official 3.12.1 release
    --     -- 4.00.0  Official 4.00.0 release
    --     -- 4.00.1  Official 4.00.1 release
    --     -- 4.01.0  Official 4.01.0 release
    --     -- 4.02.0  Official 4.02.0 release
    --     -- 4.02.1  Official 4.02.1 release
    system  C system  System compiler (4.02.1)

**Comment by vzaliva** [comment]
The later issue seems to be unrelated to the original problem, so I've opened a separate report for it: #4105 

I will close this one once I am able to upgrade "camlp" and verify that it helps.

**Comment by vzaliva** [comment]
I switched from system to OPAM-maintained compiler and installed camlp-4.02.1+2 as suggested.
After that it still does not work.  Now "#require" command succeeds, but an attempt to define type hangs:

    # #require "deriving.syntax";;
    # type sum = S0 | S1 of int | S2 of int * float | S3 of int * float * bool | Sunit of unit | Stup of (int * float) |     Stup1 of (int)
      deriving (Dump, Eq, Show, Typeable, Pickle)  ;;
    
      ^C Interrupted.

**Comment by yallop** [comment]
I'm also seeing deriving hang in the top-level, although not at exactly the same point.  You may be able to get more help on the [deriving issue tracker](https://github.com/ocsigen/deriving).

**Comment by samoht** [comment]
Closing as the issue has been reported upstream.
